/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IntentRouteImport } from './routes/intent'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as CookRouteImport } from './routes/cook'
import { Route as IndexRouteImport } from './routes/index'

const IntentRoute = IntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRoute = CookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/decision': typeof DecisionRoute
  '/feedback': typeof FeedbackRoute
  '/intent': typeof IntentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/decision': typeof DecisionRoute
  '/feedback': typeof FeedbackRoute
  '/intent': typeof IntentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/decision': typeof DecisionRoute
  '/feedback': typeof FeedbackRoute
  '/intent': typeof IntentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cook' | '/decision' | '/feedback' | '/intent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cook' | '/decision' | '/feedback' | '/intent'
  id: '__root__' | '/' | '/cook' | '/decision' | '/feedback' | '/intent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookRoute: typeof CookRoute
  DecisionRoute: typeof DecisionRoute
  FeedbackRoute: typeof FeedbackRoute
  IntentRoute: typeof IntentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/intent': {
      id: '/intent'
      path: '/intent'
      fullPath: '/intent'
      preLoaderRoute: typeof IntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook': {
      id: '/cook'
      path: '/cook'
      fullPath: '/cook'
      preLoaderRoute: typeof CookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookRoute: CookRoute,
  DecisionRoute: DecisionRoute,
  FeedbackRoute: FeedbackRoute,
  IntentRoute: IntentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
